Flask_App/__init__.py
# contains the create_app function which is the application factory function
import os

from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from .main import main
from config import config

# extensions
bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
# db = SQLAlchemy()


def create_app(config_name=None):
    # create and configure the app. 
    app = Flask(__name__, instance_relative_config=True)

    # Configuration using an object or a custom config name
    if config_name is not None:
        app.config.from_object(config[config_name])
        config[config_name].init_app(app)
    else:
        app.config.from_mapping(
            SECRET_KEY='dev',
            DATABASE=os.path.join(app.instance_path, 'flask_app.sqlite'),
            )

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # initialize extensions within the app
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)

    # a simple page that says hello
    @app.route('/hello')
    def hello():
        return 'Hello Wice'
    
    # register blueprints
    from . import db, auth
    from .main import main as main_bp
    db.init_app(app)

    app.register_blueprint(auth.auth_bp)
    app.register_blueprint(main_bp)

    
    return app

Flask_App/auth.py
# contains the blueprint for the authentication functions

import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash, generate_password_hash

from Flask_App.db import get_db

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

@auth_bp.route('/register', methods=('GET', 'POST'))
def register():
    # the register view function
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        if not username:
            error = 'Username is required!'
        elif not password:
            error = 'Password is required.'

        if error is None:
            try:
                db.execute(
                    """
                    INSERT INTO user (username, password) VALUES (?, ?)""",
                    (username, generate_password_hash(password)),
                )
                db.commit()
            except db.IntegrityError:
                error = f"User {username} is already registered!"
            else:
                return redirect(url_for("auth.login"))
            
        flash(error)

    return render_template('auth/register.html')


@auth_bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        db = get_db()
        error = None

        user = db.execute(""" SELECT * FROM user WHERE username = ? """, (username,)).fetchone()

        if user is None:
            error = "Incorrect username, check your spelling!"
        elif not check_password_hash(user['password'], password):
            error = "Incorrect password, try again."

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('main.index'))
        
        flash(error)

    return render_template('auth/login.html')


@auth_bp.before_app_request
def load_logged_in_user():
    # auth_bp.before_app_request registers a function that runs before the view function,
    # no matter what URL is requested.

    # load_logged_in_user - function checks if a user id is stored in the session and gets 
    # the user's data from the database, storing it on g.user, which lasts for the lenght of
    # the request.
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = get_db().execute(
            """ SELECT * FROM user WHERE id = ? """, (user_id,)
        ).fetchone()


@auth_bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    # this decorator returns a new view function that wraps the original view it's applied to.
    # the new function checks if a user is loaded and redirects to the login page otherwise.

    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        
        return view(**kwargs)
    
    return wrapped_view

Flask_App/main/__init__.py
# contains the blueprint for the main application functions

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)

from werkzeug.exceptions import abort

main = Blueprint('main', __name__)

from . import views, errors

Flask_App/main/views.py
# contains the blueprint for the main application functions

from datetime import datetime
from . import main
import functools
from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.exceptions import abort
from Flask_App.auth import login_required
from Flask_App.db import get_db


@main.route('/')
def index():
    db = get_db()
    posts = db.execute(
        'SELECT p.id, title, body, created, author_id, username'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' ORDER BY created DESC'
    ).fetchall()
    return render_template('main/index.html', posts=posts)

@main.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'INSERT INTO post (title, body, author_id)'
                ' VALUES (?, ?, ?)',
                (title, body, g.user['id'])
            )
            db.commit()
            return redirect(url_for('main.index'))

    return render_template('main/create.html')

def get_post(id, check_author=True):
    post = get_db().execute(
        'SELECT p.id, title, body, created, author_id, username'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' WHERE p.id = ?',
        (id,)
    ).fetchone()

    if post is None:
        abort(404, f"Post id {id} doesn't exist.")

    if check_author and post['author_id'] != g.user['id']:
        abort(403)

    return post

@main.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    post = get_post(id)

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            db = get_db()
            db.execute(
                'UPDATE post SET title = ?, body = ?'
                ' WHERE id = ?',
                (title, body, id)
            )
            db.commit()
            return redirect(url_for('main.index'))

    return render_template('main/update.html', post=post)

@main.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    get_post(id)
    db = get_db()
    db.execute('DELETE FROM post WHERE id = ?', (id,))
    db.commit()
    return redirect(url_for('main.index'))

Flask_App/templates/base.html
<!DOCTYPE html>
<title> {% block title%}{% endblock %} - Flask_App </title> 
<!-- the above block will change the title displayed in the browser's tab and window title -->
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
    <h1> Flask_App </h1>
    <ul>
        {% if g.user %}
        <li>
            <span>{{ g.user['username'] }} </span>
        </li>
        <li>
            <a href="{{ url_for('auth.logout') }}"> Log Out</a>
        </li>
        {% else %}
        <li>
            <a href="{{ url_for('auth.register') }}"> Register</a>
            <a href="{{ url_for('auth.login') }}"> Login</a>
        </li>
        {% endif %}
    </ul>
</nav>
<section class="content">
    <header>
        {% block header %}{% endblock %}
        <!-- is similar to title but will change the title displayed on the page -->
    </header>
    {% for message in get_flashed_messages() %}
    <div class="flash">
        {{ message }}
    </div>
    {% endfor %}
    {% block content %}{% endblock %}
    <!-- where the content of each page goes, such as the login form or any other page -->
</section>

Flask_App/templates/main/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title" value="{{ request.form['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
{% endblock %}

Flask_App/templates/main/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Posts{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('main.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in posts %}
    <article class="post">
      <header>
        <div>
          <h1>{{ post['title'] }}</h1>
          <div class="about">by {{ post['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == post['author_id'] %}
          <a class="action" href="{{ url_for('main.update', id=post['id']) }}">Edit</a>
        {% endif %}
      </header>
      <p class="body">{{ post['body'] }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

Flask_App/templates/main/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ post['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title"
      value="{{ request.form['title'] or post['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ url_for('main.delete', id=post['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}